# Generated by Django 5.0.6 on 2025-11-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField()),
                ('aadhaar_image', models.ImageField(upload_to='aadhaar/')),
                ('profile_photo', models.ImageField(upload_to='profile/')),
                ('joining_date', models.DateField()),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
