# Generated by Django 5.0.6 on 2025-11-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('dob', models.DateField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='nurse_profile/')),
                ('aadhaar_image', models.ImageField(blank=True, null=True, upload_to='nurse_aadhaar/')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('pin_code', models.CharField(max_length=10)),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='nurse_certificates/')),
                ('experience', models.CharField(max_length=200)),
                ('joining_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
