# Generated by Django 5.0.6 on 2025-11-20 08:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_inquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('attendant_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('patient_photo', models.ImageField(blank=True, null=True, upload_to='patient_photo/')),
                ('attendant_photo', models.ImageField(blank=True, null=True, upload_to='attendant_photo/')),
                ('patient_aadhar', models.ImageField(blank=True, null=True, upload_to='patient_aadhar/')),
                ('attendant_aadhar', models.ImageField(blank=True, null=True, upload_to='attendant_aadhar/')),
                ('attendant_pan', models.ImageField(blank=True, null=True, upload_to='attendant_pan/')),
                ('attendant_signature', models.ImageField(blank=True, null=True, upload_to='attendant_signature/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NurseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.nurse')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
    ]
