# Generated by Django 5.0.6 on 2025-11-21 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_patient_nurseassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_rate', models.FloatField(default=1000)),
                ('daily_rate_set', models.BooleanField(default=False)),
                ('days_worked', models.PositiveIntegerField(default=0)),
                ('total_bill', models.FloatField(default=0)),
                ('amount_paid', models.FloatField(default=0)),
                ('payment_mode', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('UPI', 'UPI')], max_length=10, null=True)),
                ('utr_number', models.CharField(blank=True, max_length=50, null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='payment_screenshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
    ]
