# Generated by Django 5.0.6 on 2025-11-22 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_payment_amount_paid_remove_payment_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('date_of_joining', models.DateField()),
                ('passbook_image', models.ImageField(blank=True, null=True, upload_to='passbook/')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('monthly_salary', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_date', models.DateField(auto_now_add=True)),
                ('amount_paid', models.PositiveIntegerField()),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI')], max_length=10)),
                ('utr_no', models.CharField(blank=True, max_length=200, null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='payment_screenshot/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.employee')),
            ],
        ),
    ]
