# Generated by Django 5.0.6 on 2025-11-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_employee_employeepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
