# Generated by Django 5.0.6 on 2025-11-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_inquiry_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='parents_aadhaar_image',
            field=models.ImageField(blank=True, null=True, upload_to='nurse_parents_aadhaar/'),
        ),
        migrations.AddField(
            model_name='nurse',
            name='parents_contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
