# Generated by Django 5.0.6 on 2025-11-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_nurse_parents_aadhaar_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='parents_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
