# Generated by Django 5.0.6 on 2025-11-27 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_nurse_parents_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeepayment',
            name='employee',
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nurse')),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='EmployeePayment',
        ),
    ]
