# Generated by Django 5.0.6 on 2025-11-27 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_employeepayment_employee_attendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NursePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('per_day_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_working_days', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI')], max_length=20)),
                ('utr_number', models.CharField(blank=True, max_length=100, null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='payment_screenshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nurse')),
            ],
        ),
    ]
