# Generated by Django 5.0.6 on 2025-11-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_nursepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursepayment',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount paid to nurse', max_digits=12),
        ),
        migrations.AlterField(
            model_name='nursepayment',
            name='per_day_salary',
            field=models.DecimalField(decimal_places=2, help_text='Salary per working day', max_digits=10),
        ),
        migrations.AlterField(
            model_name='nursepayment',
            name='screenshot',
            field=models.ImageField(blank=True, help_text='Upload payment screenshot if UPI', null=True, upload_to='payment_screenshots/'),
        ),
        migrations.AlterField(
            model_name='nursepayment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Calculated total amount = per_day_salary * total_working_days', max_digits=12),
        ),
        migrations.AlterField(
            model_name='nursepayment',
            name='total_working_days',
            field=models.IntegerField(help_text='Total working days in the month'),
        ),
        migrations.AlterField(
            model_name='nursepayment',
            name='utr_number',
            field=models.CharField(blank=True, help_text='UTR number if payment via UPI', max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='nursepayment',
            unique_together={('nurse', 'month', 'year')},
        ),
    ]
