# Generated by Django 5.0.6 on 2025-11-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_nursepayment_paid_amount_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nursepayment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='nursepayment',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nursepayment',
            name='per_day_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nursepayment',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/'),
        ),
        migrations.AlterField(
            model_name='nursepayment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nursepayment',
            name='total_working_days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nursepayment',
            name='utr_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
