# Generated by Django 5.0.6 on 2026-06-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_nursepayment_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurseassignment',
            name='nurse',
        ),
        migrations.RemoveField(
            model_name='nurseassignment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='nursepayment',
            name='nurse',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='paymententry',
            name='payment',
        ),
        migrations.AddField(
            model_name='nurse',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='NurseAssignment',
        ),
        migrations.DeleteModel(
            name='NursePayment',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentEntry',
        ),
    ]
