# Generated by Django 5.0.6 on 2026-06-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_nurseassignment_nurse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
