# Generated by Django 5.0.6 on 2026-06-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_nurse_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='patient_profile/')),
                ('address', models.TextField()),
                ('pin_code', models.CharField(max_length=10)),
                ('aadhaar_image', models.ImageField(upload_to='patient_aadhaar/')),
                ('agreement_image', models.ImageField(blank=True, null=True, upload_to='patient_agreement/')),
                ('patient_representative_name', models.CharField(max_length=200)),
                ('patient_representative_phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=200)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
