# Generated by Django 5.0.6 on 2026-06-11 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('admin_remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='app.nurse')),
            ],
            options={
                'ordering': ['-from_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemporaryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_assignments', to='app.nurseleave')),
                ('original_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_assignments', to='app.nurseassignment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_assignments', to='app.patient')),
                ('replacement_nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_assignments_as_replacement', to='app.nurse')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
