# Generated by Django 5.0.6 on 2026-06-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_nurseleave_temporaryassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryassignment',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
