# Generated by Django 5.0.6 on 2026-06-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_temporaryassignment_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryassignment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
